export def main [] {
    let root = $"($env.HOME)/.config/mcp"
    let generated = $"($root)/generated"

    mkdir $generated
    mkdir $"($generated)/launchd"

    let cfg = openn $"($root)/mcp.toml"

    # Generate mise config
    let mise_root = $"($env.HOME)/.config/mise"
    let mise_config = $"($mise_root)/config.mcp.toml"

    mkdir $mise_root

    let mcp_entries = ($cfg.mcp | transpose name value)

    let tasks = (
        $mcp_entries
        | reduce -f {} { |it, acc|
            let input_type_raw = ($it.value | get -o type)
            let proxy_type_raw = ($it.value | get -o supergatewayProxy)

            let input_type = ($input_type_raw | default "stdio")
            let proxy_type = ($proxy_type_raw | default $input_type)

            let has_http_binding = (($it.value | get -o port) != null) and (($it.value | get -o path) != null)
            let inferred_direct_http = (($input_type_raw == null) and ($proxy_type_raw == null) and $has_http_binding)

            let use_supergateway = ($input_type != $proxy_type)

            let input_arg = if $use_supergateway {
                (match $input_type {
                    "stdio" => $"--stdio \"($it.value.run)\""
                    "sse" => $"--sse \"($it.value.run)\""
                    "streamableHttp" => $"--streamableHttp \"($it.value.run)\""
                    _ => (error make {msg: $"Unsupported mcp.($it.name).type: ($input_type)"})
                })
            } else {
                ""
            }

            let proxy_arg = if $use_supergateway {
                (match $proxy_type {
                    "stdio" => "--outputTransport stdio"
                    "sse" => "--outputTransport sse"
                    "streamableHttp" => "--outputTransport streamableHttp"
                    _ => (error make {msg: $"Unsupported mcp.($it.name).supergatewayProxy: ($proxy_type)"})
                })
            } else {
                ""
            }

            let proxied_run = if $use_supergateway {
                if $proxy_type == "stdio" {
                    $"($cfg.env.SUPERGATEWAY_CMD) ($input_arg) ($proxy_arg)"
                } else {
                    $"($cfg.env.SUPERGATEWAY_CMD) ($input_arg) ($proxy_arg) --port ($it.value.port) --cors"
                }
            } else {
                ""
            }

            let task_name = $"mcp-($it.name)"
            let task_run = if $use_supergateway { $proxied_run } else { $it.value.run }
            let task_mode = if $use_supergateway {
                $"($input_type) -> ($proxy_type) via supergateway"
            } else if $inferred_direct_http {
                "direct (inferred streamableHttp)"
            } else {
                $"direct ($input_type)"
            }

            $acc | insert $task_name {
                description: ($it.value.description + " (" + $task_mode + ")")
                run: $task_run
            }
        }
    )

    let mise_toml = (
        {
            env: $cfg.env
            tools: $cfg.tools
            tasks: $tasks
        }
        | to toml
    )

    $"# Generated by ~/.config/mcp/generate-mcp.nu\n# using ~/.config/mcp/mcp.toml as template\n\n($mise_toml)"
    | save -f $mise_config

    # Generate Caddyfile
    let caddy = (
        $mcp_entries
        | each { |it|
            let input_type_raw = ($it.value | get -o type)
            let proxy_type_raw = ($it.value | get -o supergatewayProxy)

            let input_type = ($input_type_raw | default "stdio")
            let proxy_type = ($proxy_type_raw | default $input_type)

            let has_http_binding = (($it.value | get -o port) != null) and (($it.value | get -o path) != null)
            let inferred_direct_http = (($input_type_raw == null) and ($proxy_type_raw == null) and $has_http_binding)

            let effective_type = if $inferred_direct_http {
                "streamableHttp"
            } else if $input_type != $proxy_type {
                $proxy_type
            } else {
                $input_type
            }

            if ($has_http_binding and ($effective_type == "streamableHttp" or $effective_type == "sse")) {
                let main_route = $"    handle_path ($it.value.path)* {\n        reverse_proxy localhost:($it.value.port)\n    }\n"

                # MCP Inspector serves static assets from absolute root paths (/assets/*, /mcp.svg)
                # so when proxied under /inspector we must expose those root paths as well.
                let inspector_root_assets = if ($it.name == "inspector" and $it.value.path != "/") {
                    $"\n    handle /assets* {\n        reverse_proxy localhost:($it.value.port)\n    }\n\n    handle /mcp.svg {\n        reverse_proxy localhost:($it.value.port)\n    }\n"
                } else {
                    ""
                }

                $"($main_route)($inspector_root_assets)"
            } else {
                ""
            }
        }
        | where {|line| $line != ""}
        | str join "\n"
    )

    $":8765 {\n\n($caddy)\n}" | save -f $"($generated)/Caddyfile"

    # Generate launchd plists
    $mcp_entries
    | each { |it|
        let input_type_raw = ($it.value | get -o type)
        let proxy_type_raw = ($it.value | get -o supergatewayProxy)

        let input_type = ($input_type_raw | default "stdio")
        let proxy_type = ($proxy_type_raw | default $input_type)

        let has_http_binding = (($it.value | get -o port) != null) and (($it.value | get -o path) != null)
        let inferred_direct_http = (($input_type_raw == null) and ($proxy_type_raw == null) and $has_http_binding)

        let effective_type = if $inferred_direct_http {
            "streamableHttp"
        } else if $input_type != $proxy_type {
            $proxy_type
        } else {
            $input_type
        }

        if ($has_http_binding and ($effective_type == "streamableHttp" or $effective_type == "sse")) {
            let plist = $"
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"
 \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">

<plist version=\"1.0\">
<dict>

  <key>Label</key>
  <string>dev.mcp.($it.name)</string>

  <key>ProgramArguments</key>
  <array>
    <string>/opt/homebrew/bin/mise</string>
    <string>run</string>
    <string>mcp-($it.name)</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>/tmp/mcp-($it.name).stdout.log</string>

  <key>StandardErrorPath</key>
  <string>/tmp/mcp-($it.name).stderr.log</string>

</dict>
</plist>
"

            $plist | save -f $"($generated)/launchd/dev.mcp.($it.name).plist"
        }
    }

    # Generate launchd plist for Caddy (run through mise so caddy binary lookup is deterministic)
    let caddy_plist = $"
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"
 \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">

<plist version=\"1.0\">
<dict>

  <key>Label</key>
  <string>dev.caddy</string>

  <key>ProgramArguments</key>
  <array>
    <string>/opt/homebrew/bin/mise</string>
    <string>x</string>
    <string>caddy@latest</string>
    <string>--</string>
    <string>caddy</string>
    <string>run</string>
    <string>--config</string>
    <string>($generated)/Caddyfile</string>
    <string>--adapter</string>
    <string>caddyfile</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>/tmp/caddy.stdout.log</string>

  <key>StandardErrorPath</key>
  <string>/tmp/caddy.stderr.log</string>

</dict>
</plist>
"

    $caddy_plist | save -f $"($generated)/launchd/dev.caddy.plist"
}
